// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: proto/activity/activity.proto

package yuemnoi_activity

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ActivityLogService_CreateActivityLog_FullMethodName   = "/ActivityLogService/CreateActivityLog"
	ActivityLogService_ViewActivityHistory_FullMethodName = "/ActivityLogService/ViewActivityHistory"
)

// ActivityLogServiceClient is the client API for ActivityLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActivityLogServiceClient interface {
	CreateActivityLog(ctx context.Context, in *CreateActivityLogRequest, opts ...grpc.CallOption) (*CreateActivityLogResponse, error)
	ViewActivityHistory(ctx context.Context, in *ViewActivityHistoryRequest, opts ...grpc.CallOption) (*ViewActivityHistoryResponse, error)
}

type activityLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewActivityLogServiceClient(cc grpc.ClientConnInterface) ActivityLogServiceClient {
	return &activityLogServiceClient{cc}
}

func (c *activityLogServiceClient) CreateActivityLog(ctx context.Context, in *CreateActivityLogRequest, opts ...grpc.CallOption) (*CreateActivityLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateActivityLogResponse)
	err := c.cc.Invoke(ctx, ActivityLogService_CreateActivityLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityLogServiceClient) ViewActivityHistory(ctx context.Context, in *ViewActivityHistoryRequest, opts ...grpc.CallOption) (*ViewActivityHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewActivityHistoryResponse)
	err := c.cc.Invoke(ctx, ActivityLogService_ViewActivityHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityLogServiceServer is the server API for ActivityLogService service.
// All implementations must embed UnimplementedActivityLogServiceServer
// for forward compatibility.
type ActivityLogServiceServer interface {
	CreateActivityLog(context.Context, *CreateActivityLogRequest) (*CreateActivityLogResponse, error)
	ViewActivityHistory(context.Context, *ViewActivityHistoryRequest) (*ViewActivityHistoryResponse, error)
	mustEmbedUnimplementedActivityLogServiceServer()
}

// UnimplementedActivityLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActivityLogServiceServer struct{}

func (UnimplementedActivityLogServiceServer) CreateActivityLog(context.Context, *CreateActivityLogRequest) (*CreateActivityLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateActivityLog not implemented")
}
func (UnimplementedActivityLogServiceServer) ViewActivityHistory(context.Context, *ViewActivityHistoryRequest) (*ViewActivityHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewActivityHistory not implemented")
}
func (UnimplementedActivityLogServiceServer) mustEmbedUnimplementedActivityLogServiceServer() {}
func (UnimplementedActivityLogServiceServer) testEmbeddedByValue()                            {}

// UnsafeActivityLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivityLogServiceServer will
// result in compilation errors.
type UnsafeActivityLogServiceServer interface {
	mustEmbedUnimplementedActivityLogServiceServer()
}

func RegisterActivityLogServiceServer(s grpc.ServiceRegistrar, srv ActivityLogServiceServer) {
	// If the following call pancis, it indicates UnimplementedActivityLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ActivityLogService_ServiceDesc, srv)
}

func _ActivityLogService_CreateActivityLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateActivityLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityLogServiceServer).CreateActivityLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivityLogService_CreateActivityLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityLogServiceServer).CreateActivityLog(ctx, req.(*CreateActivityLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityLogService_ViewActivityHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewActivityHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityLogServiceServer).ViewActivityHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivityLogService_ViewActivityHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityLogServiceServer).ViewActivityHistory(ctx, req.(*ViewActivityHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ActivityLogService_ServiceDesc is the grpc.ServiceDesc for ActivityLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActivityLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ActivityLogService",
	HandlerType: (*ActivityLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateActivityLog",
			Handler:    _ActivityLogService_CreateActivityLog_Handler,
		},
		{
			MethodName: "ViewActivityHistory",
			Handler:    _ActivityLogService_ViewActivityHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/activity/activity.proto",
}
